# Generated by Django 2.2 on 2019-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
